version: '3'
services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # grpc-client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   depends_on:
  #     - grpc-server
